controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - l_shoulder_pan
        - l_shoulder_lift
        - l_elbow_flex
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

    right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - r_hip_pitch
        - r_knee_pitch
        - r_ankle_pitch
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
